### ISSUE TITLE
can twurl but not get account info through node module

### ISSUE THREAD

**Issue by hiddenkirby** [FallenTech/twitter-ads#1]
I posted a SO question as well.  https://stackoverflow.com/questions/45202177/nodejs-twitter-ads-lib-cannot-find-my-account-account-myaccountnumber-was-not

Any help is appreciated. 

I'm assuming there is some difference with accessing via app access tokens?

**Comment by hiddenkirby** [comment]
The question got an answer. I'll do PR with an addition to the documentation later today.

**Comment by talha-asad** [comment]
Yeah it doesn't seem very clear from the documentation where that configuration has to go. I am submitting a fix for this.
