### ISSUE TITLE
T.tonUpload getting status 400 Error

### ISSUE THREAD

**Issue by jme900** [FallenTech/twitter-ads#2]
I am getting `Error: TwitterAdsAPI: Twitter TON API returned HTTP status code: 400` every time I attempt to upload my audience file using the T.tonUpload endpoint. I have authenticated with Twitter and successfully used the endpoint T.get('/accounts... with no issues.

Looking at the docs on https://dev.twitter.com/rest/ton it seems like there is suppose to be a  `'x-ton-expires'` header, which I tried (see below), but I still get the same error. @talha-asad do you have any ideas?

My Code:
```javascript
var T = new TwitterAdsAPI({
  consumer_key: adApp.consumer_key,
  consumer_secret: adApp.consumer_secret,
  access_token: adApp.access_token,
  access_token_secret: adApp.access_token_secret,
  sandbox: false,
  api_version: '2'
});
T.tonUpload({
    file: dir,
    content_type: 'text/plain',
    bucket_name: 'ta_partner',
    'x-ton-expires': expires
  },
  function(error, location) {
    if (error) return res.serverError(error);
    return res.ok(location);
    /* If everything goes okay,
     you should get something similar to this:
     https://ton.twitter.com/1.1/ton/bucket/ta_partner/2892314386/n3UPAcC02roTP6C
     */
  });
});
```

**Comment by talha-asad** [comment]
What is the file extension of the file you are uploading, in our experience twitter doesn't allow certain file extensions for certain buckets. This is not mentioned in their docs. Does the same file upload fine using twurl?

**Comment by jme900** [comment]
Thank you for the response @talha-asad. I have tried Twurl. I'm currently experiencing [this](https://twittercommunity.com/t/uploading-user-ids-for-tailored-audience-ton/69322/3) exact problem. Twurl --data works, but I'm getting the same error (as I posted originally) when using Twurl --file.

I've built a test csv file with one hashed id, as well as a file with 1,000 hashed ids. Neither works with Twurl or twitter-ads.

One question for you, does your wrapper support only uploading a file? Or is there another way - something like Twurl's --data option?

**Comment by talha-asad** [comment]
Try removing the 'x-ton-expires'

**Comment by jme900** [comment]
Removing x-ton-expires did not help. I was able to use your source code and use 'request' to write my own upload file function, which didn't require a file (I uploaded it using the body). Because I've got a working solution, I will close this issue. Thanks for your help tho.
``` javascript
var oauth= {
  consumer_key: app.consumer_key,
  consumer_secret: app.consumer_secret,
  token: app.access_token,
  token_secret: app.access_token_secret
};
var expireTime = moment().utc().add(7, 'days').toDate().toUTCString();
var size = Buffer.byteLength(dataToUpload, 'utf8');
var header = {
  "Content-Length": size,
  "Content-Type": "text/plain",
  "X-TON-Content-Length": size,
  "X-TON-Content-Type": "text/plain",
  "X-TON-Expires": expireTime
};
request.post({
  url:"https://ton.twitter.com/1.1/ton/bucket/ta_partner",
  headers:header,
  oauth:oauth,
  body:dataToUpload
}, function(err, resp, bod) {
  var response ={
    error:err,
    response:resp,
    body:bod,
    comment:"Step 1: file upload failed"
  };
  if(err || !resp.headers || !resp.headers.location) cb(response);
  var location = resp.headers.location;
  console.log("LOCATION: "+location);
  //use location for further calls to ton.twitter.com or just return it
  return location;
});
```
